
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/nav/NavBar";
import Footer from "./components/footer/Footer";
import { CartProvider } from "./context/CartProvider";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "./context/AuthProvider";
import Providers from "@/app/providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-commerce | Flipkart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">


      <body className={`${geistSans.variable} text-slate-700`}>
        <Providers>
          <Toaster toastOptions={{
            style: {
              background: 'rgb(51 65 85)',
              color: '#fff',
            }
          }} />
          <AuthProvider>
            <CartProvider>
              <NavBar />
              <main className="grow">{children}</main>
              <Footer />
            </CartProvider>
          </AuthProvider>


        </Providers>

      </body>
    </html>
  );
}
